# -*- coding: utf-8 -*-
"""image-colorization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tuiuz1WYpGys0ilek4_kEtSTwbLPcrKN
"""



# Clone deoldify Repository
# !git clone https://github.com/jantic/DeOldify.git DeOldify

# Commented out IPython magic to ensure Python compatibility.
# %cd DeOldify

#!pip install -r requirements-colab.txt

#!pip install -U fastai

# import pytorch library
import torch
# check for GPU
if not torch.cuda.is_available():
    print('GPU not available.')

# necessary imports
import fastai
from DeOldify.visualize import *
import warnings
warnings.filterwarnings("ignore",
                        category=UserWarning, message=".*?Your .*? set is empty.*?")

# download the artistic model
#!mkdir 'models'
#!wget https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth -O ./models/ColorizeArtistic_gen.pth

# use the get image colorizer function with artistic model
colorizer = get_image_colorizer(artistic=True)

# Specify the path to your input image file
input_image_path = input_image_path = 'C:\\Users\\malky\\Desktop\\image-colorization\\old-black-and-white-photo-colorization-retro-brush-fb21.png'


# Provide the parameters such as render factor etc.
render_factor = 39 #@param {type: "slider", min: 7, max: 40"}
watermarked = False #@param {type:"boolean"}

if input_image_path is not None and input_image_path != '':
    image_path = colorizer.plot_transformed_image(input_image_path,
          render_factor=render_factor, compare=True, watermarked=watermarked)
    show_image_in_notebook(image_path)
else:
    print('Provide a valid input image path.')